GET http://localhost:8800/api/auth/me HTTP/1.1


### content-type เว้น 1 บรรทัด
POST http://localhost:8800/api/post  HTTP/1.1
Content-Type: application/json

{
  # "message" : "Hello CC20"
  "message" : "Hello , CC21"
}


###
POST  http://localhost:8800/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "message": "Hello , CC21"
}


### Day2
## Register Api
POST http://localhost:8800/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "identity": "andy@ggg.mail",
  "mobile": "1234567890",
  "firstName": "someone",
  "lastName": "Codecamp",
  "password": "123456",
  "confirmPassword": "123456"
}

###
# Login Api
POST http://localhost:8800/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "identity" : "andy@ggg.mail",
    "password" : "123456"
}